### ISSUE TITLE
Error when using Next.js turbo 

### ISSUE THREAD

**Issue by ariperez** [clerkinc/javascript#1257]
- [x] Review the documentation: https://clerk.com/docs
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [ ] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [x] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

### Dependencies + versions

Provide a json with the dependencies used in your project (copy paste from yarn.lock / package-lock.json) or a github project / template that reproduces the issue.

**Include the @clerk/* packages and their versions!**

Example:

```json
{  
  "dependencies": {
    "next": "13.4.4",
  },
  "devDependencies": {
    "@clerk/clerk-sdk-node": "^4.10.2",
    "@clerk/nextjs": "^4.19.0",
  },
  "peerDependencies": {
    "react": "18.2.0"
  }
}

```

## Description

when attempting to run the latest version of Next.js with Turbopack enabled, the following error originates from @clerk/nextjs.

```
npm run dev --turbo
```

```
error during Next.js routing for /

Caused by:
- Error: Cannot find module '#crypto'

Debug info:
- Execution of get_from_source failed
- Execution of resolve_source_request failed
- Execution of NextRouterContentSource::get failed
- error during Next.js routing for /
- Error: Cannot find module '#crypto'
      [at file:///Users/ariperez/github/coa-solutions/app/.next/build/edge/chunks/[next]_entry_edge-bootstrap.ts_00208c._.js]
      [at file:///Users/ariperez/github/coa-solutions/app/.next/build/edge/chunks/node_modules_0367fb._.js:13896:15]
      [at file:///Users/ariperez/github/coa-solutions/app/.next/build/edge/chunks/node_modules_0367fb._.js:13899:3]
      [at [project]/node_modules/@clerk/backend/dist/esm/index.js (ecmascript) (file:///Users/ariperez/github/coa-solutions/app/.next/build/edge/chunks/node_modules_0367fb._.js:15738:3)]
      [at file:///Users/ariperez/github/coa-solutions/app/.next/build/edge/chunks/[next]_entry_edge-bootstrap.ts_00208c._.js:497:21]
      [at runModuleExecutionHooks (file:///Users/ariperez/github/coa-solutions/app/.next/build/edge/chunks/[next]_entry_edge-bootstrap.ts_00208c._.js:544:5)]
      [at instantiateModule (file:///Users/ariperez/github/coa-solutions/app/.next/build/edge/chunks/[next]_entry_edge-bootstrap.ts_00208c._.js:496:5)]
      [at getOrInstantiateModuleFromParent (file:///Users/ariperez/github/coa-solutions/app/.next/build/edge/chunks/[next]_entry_edge-bootstrap.ts_00208c._.js:593:10)]
      [at esmImport (file:///Users/ariperez/github/coa-solutions/app/.next/build/edge/chunks/[next]_entry_edge-bootstrap.ts_00208c._.js:217:18)]
      [at file:///Users/ariperez/github/coa-solutions/app/.next/build/edge/chunks/node_modules_0367fb._.js:16316:142]
      [at [project]/node_modules/@clerk/nextjs/dist/esm/server/getAuth.js (ecmascript) (file:///Users/ariperez/github/coa-solutions/app/.next/build/edge/chunks/node_modules_0367fb._.js:16405:3)]
```

**Comment by doneumark** [comment]
Experiencing the same problem!

**Comment by nikosdouvlis** [comment]
Hello everyone, we're currently working with the NextJS team to get all Turbopack-related issues solved. I don't currently have a strict timeline I can share as this an upstream dependency, but I'll probably have more updates towards the end of this week.

Related issues on the NextJS repo:
- https://github.com/vercel/next.js/issues/45371
- https://github.com/vercel/next.js/pull/50567

**Comment by YahiaElTai** [comment]
Experiencing the same issue as well.

**Comment by clerk-cookie** [comment]
This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days.

**Comment by clerk-cookie** [comment]
This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days.

**Comment by clerk-cookie** [comment]
This issue was closed because it has been stalled for 10 days with no activity.

**Comment by obabovic** [comment]
Any update on this matter? I'm using turborepo + NestJS + Jest. When trying to import a module that references any of Clerk entities inside `.spec` (Jest) files, I get to the same error - `cannot find module #crypto`. Went into `node_modules/.pnpm/@clerk+backend@0.28.1/node_modules/@clerk/backend/dist/index.js`, I can see:
```
...
var import_crypto = __toESM(require("#crypto"));
var fetchApisPolyfill = __toESM(require("#fetch"));
```
Both of these can't actually be found.

What to do here?

**Comment by dimkl** [comment]
Hello @obabovic ,
the issue with Jest may be related to the fact that Jest currently doesn't support package.json subpath imports, so you will have to manually add the following to your Jest file:
```
moduleNameMapper: { '#crypto': '@clerk/backend/dist/runtime/node/crypto.js', '#fetch': '@clerk/backend/dist/runtime/node/fetch.js', },
```

Could you try this?

**Comment by clerk-cookie** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
