### ISSUE TITLE
@clerk/remix@2.6.6+: Error: OrganizationContext not found

### ISSUE THREAD

**Issue by carinakoo8** [clerkinc/javascript#1360]
- [x] Review the documentation: https://clerk.com/docs
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [x] Provide the Frontend API key from your application dashboard.

CLERK_PUBLISHABLE_KEY=pk_test_aGVscGVkLWtpdHRlbi03NS5jbGVyay5hY2NvdW50cy5kZXYk

## Package + Version

- [x] `@clerk/remix`

starting in version 2.6.6

### Dependencies + versions

Provide a json with the dependencies used in your project (copy paste from yarn.lock / package-lock.json) or a github project / template that reproduces the issue.

@clerk/remix@2.6.6

Minimal repro: https://github.com/carinakoo8/clerk-remix-auth-starter

This is a clone of the Clerk remix-auth-starter repro with the following changes:
1. Upgrade @clerk/remix to 2.6.6
2. Call `useOrganization` in the index route.

### Browser/OS

Tested in Chrome and Safari

## Description

Minimal repro: https://github.com/carinakoo8/clerk-remix-auth-starter

Call to `useOrganization` results in this error, preventing the app from rendering.

```
Uncaught Error: OrganizationContext not found
    at assertContextExists (createContextAndHook.ts:5:42)
    at useCtx (createContextAndHook.ts:29:5)
    at useOrganization (useOrganization.tsx:45:80)
    at Index (index.tsx:125:38)
    at renderWithHooks (react-dom.development.js:14985:18)
    at mountIndeterminateComponent (react-dom.development.js:17811:13)
    at beginWork (react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
```

**Comment by carinakoo8** [comment]
Resolved this issue by importing components from `@clerk/remix` instead of `@clerk/clerk-react`

**Comment by clerk-cookie** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
