### ISSUE TITLE
Clerk's Remix integration uses the deprecated useTransition hook

### ISSUE THREAD

**Issue by tmcw** [clerkinc/javascript#974]
- [x] Review the documentation: https://docs.clerk.com/
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [x] Provide the Frontend API key from your application dashboard.

## Package + Version

- [x] `@clerk/remix`: @clerk/remix@2.2.17

### Dependencies + versions

Provide a json with the dependencies used in your project (copy paste from yarn.lock / package-lock.json) or a github project / template that reproduces the issue.

**Please remember to include the `@clerk/*` packages and their versions!!**

Example:

```json
{  
  "dependencies": {
    "react": "18.2.0",
    "@remix-run/node": "^1.14.3",
    "@remix-run/react": "^1.14.3",
    "@remix-run/serve": "^1.14.3",
    "@clerk/remix": "^2.2.17"
  }
}
```

## Description

The Clerk Remix integration uses `useTransition` here:

https://github.com/clerkinc/javascript/blob/0b0c7d719abb06632f5e13c3d09ab666a1fb21b3/packages/remix/src/client/useAwaitableNavigate.tsx#L8

Which produces a warning:

```
DEPRECATED: The `useTransition` hook has been deprecated in favor of `useNavigation` and will be removed in Remix v2.  Please update your code to leverage `useNavigation`.

See https://remix.run/docs/hooks/use-transition and https://remix.run/docs/hooks/use-navigation for more information. 
    at ClerkProvider (http://localhost:3000/build/_shared/chunk-W6KANCLT.js:3922:30)
    at http://localhost:3000/build/_shared/chunk-W6KANCLT.js:3958:58
    at SentryRoot (http://localhost:3000/build/_shared/chunk-QFR7URUX.js:3568:22)
    at ErrorBoundary (http://localhost:3000/build/_shared/chunk-QFR7URUX.js:3427:5)
    at errorBoundary(SentryRoot)
```

**Comment by dimkl** [comment]
Hello @tmcw 👋 .Thank you for reporting this issue.
We have opened an internal ticket to handle all the required changes to support  `Remix v2`. 
You can find similar to Remix v2 issues with `remix-v2-upgrade` tag.

**Comment by ZeldOcarina** [comment]
Hey @dimkl do you happen to have an ETA on this by any chance?

**Comment by dimkl** [comment]
Hey @ZeldOcarina i can say for sure that we haven't planned to tackle this for the next 3 weeks. Is there a reason to prioritise resolving this warning ?

**Comment by ZeldOcarina** [comment]
Not an urgent one tbh, I was just wondering! :)

**Comment by clerk-cookie** [comment]
This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days.

**Comment by ZeldOcarina** [comment]
Hey @dimkl commenting to avoid this being closed automatically. Do you now happen to have an ETA?

**Comment by anagstef** [comment]
Hello everyone! The deprecated `useTransition` hook has been removed in PR #1266.

I'll close this issue. Feel free to re-open it if something does not work as expected. Thank you!

**Comment by clerk-cookie** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
